repositories:
  remote:
   - http://repo1.maven.org/maven2

artifacts:
  getopt4j: org.realityforge.getopt4j:getopt4j:jar:1.1
  postgresql: postgresql:postgresql:jar:9.1-901.jdbc4
  jtds: net.sourceforge.jtds:jtds:jar:1.2.7
  json: org.json:json:jar:20090211

  #
  # Used in mapping entities to json
  jackson_core: org.codehaus.jackson:jackson-core-asl:jar:1.9.4
  jackson_mapper: org.codehaus.jackson:jackson-mapper-asl:jar:1.9.4
  jackson_json: org.codehaus.jackson:jackson-jaxrs:jar:1.9.4

  #
  # Java Extensions
  javax_jsr305: com.google.code.findbugs:jsr305:jar:1.3.9

  mockito: org.mockito:mockito-all:jar:1.9.5
